# Example invocation: heat stack-create --poll -f volume.yaml myvolume
heat_template_version: 2015-10-15


parameters:
  size:
    type: number
    default: 1
    description: Size of the data volume in gigabytes


resources:

  myvolume:
    type: OS::Cinder::Volume
    properties:
      name: myencryptedvolume
      size: { get_param: size }
      volume_type: { get_resource: myvolumetype }

  volume_id:
    value: { get_resource: myvolume }

